# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: YongcanYang.GameCheatsManager
PackageVersion: 2.5.1
InstallerType: inno
Scope: machine
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/dyang886/Game-Cheats-Manager/releases/download/v2.5.1/Game.Cheats.Manager.Setup.2.5.1.exe
  InstallerSha256: 18B2A3459AEEFE989EAC264AE253E03A0098B6110D3A238E593EA677FB0CE84D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-19
