# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ScottSloan.Bili23Downloader
PackageVersion: 2.20.0
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ScottSloan/Bili23-Downloader/releases/download/v2.20.0/Bili23-Downloader_2.20.0_windows_x64.exe
  InstallerSha256: C5645CFCB42501267806AEEAE67A70EE3C63D82F402CC835FF143F9ABA56C8FA
ManifestType: installer
ManifestVersion: 1.12.0
